version: '3.8'

services:
  mysqldb:
    image: mysql:8.0.36
    container_name: mysqldb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=Password123
      - MYSQL_DATABASE=crud-db
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend-network
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.2'
        reservations:
          memory: 256M
          cpus: '0.1'

  backend-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-app
    depends_on:
      mysqldb:
        condition: service_healthy
    ports:
      - "8020:8020"
    restart: on-failure:3
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/crud-db?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Password123
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQLDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - DB_HOST=mysqldb
      - DB_NAME=crud-db
      - DB_USERNAME=root
      - DB_PASSWORD=Password123
    networks:
      - backend-network
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8020/employees/all"]
      interval: 15s
      timeout: 5s
      retries: 5

networks:
  backend-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local