kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: spring-crud-cluster
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30006
        hostPort: 30006
        protocol: TCP