spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}/${DB_NAME}?serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8020

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG